---
# tasks file for ignite-hadoop
- name: get axel
  apt:
    name: axel
    state: present

# Tasks to install Apache Ignite Hadoop Accelerator 2.1.0
- command: axel --output=apache-ignite-hadoop-2.1.0-bin.zip "https://www.apache.org/dyn/mirrors/mirrors.cgi?action=download&filename=ignite/2.1.0/apache-ignite-hadoop-2.1.0-bin.zip"
  args:
    chdir: /tmp
  register: out

- debug: var=out.stdout_lines

- template:
    src: apache-ignite-hadoop-2.1.0-bin.zip.sha1.j2
    dest: /tmp/apache-ignite-hadoop-2.1.0-bin.zip.sha1

- name: ensure downloaded Ignite Hadoop Accelerator 2.1.0
  shell: sha1sum -c apache-ignite-hadoop-2.1.0-bin.zip.sha1
  args:
    chdir: /tmp

- set_fact: ignite_home="{{ ansible_env.IGNITE_HOME|default('/opt/ignite') }}"

- file:
    path: "{{ ignite_home }}/libs"
    state: directory

- name: install Ignite Hadoop Accelerator 2.1.0
  unarchive:
    src: /tmp/apache-ignite-hadoop-2.1.0-bin.zip
    dest: "{{ ignite_home }}/libs"
    remote_src: yes

- name: XXX
  slurp:
    src: /etc/profile.d/hadoop.sh
  register: hadoopsh

- set_fact:
    HADOOP_HOME: "{{ hadoopsh['content'] | 
                     b64decode | 
                     regex_search('export HADOOP_HOME=(.+)', '\\1') }}"

- debug:
    msg: "HADOOP_HOME is {{ HADOOP_HOME[0] }}"

- name: configure Ignite file system
  template:
    src: default-config.xml.j2
    dest: "{{ ignite_home }}/config/default-config.xml"
  template:
    src: core-site.xml.j2
    dest: "{{ HADOOP_HOME[0] }}/etc/hadoop"

